name: "NodeJS - Code Gate"
on:
  pull_request:
    branches:
      - main # or the name of your main branch
    paths:
      - "ci/node/**"

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and run tests
        run: cd ci/node && npm install && npm test

      - name: Sonar Cloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: https://sonarcloud.io
          GITHUB_TOKEN: $GITHUB_TOKEN
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ci/node
          args: >
            -Dproject.settings=ci/node/sonar-project.properties
